### ISSUE TITLE
Kibana does not load when accessed from outside via Static NAT Rule

### ISSUE THREAD

**Issue by UncleRaymondo** [dtag-dev-sec/tpotce#182]
Hi Team,

Currently all honeypot ports are NAT'd through on a dedicated IP Address to their respective ports, this works fine.

For external dashboard access, I have NAT'd a different IP address, external port 443 (HTTPS) to internal port 64297. Everything works fine, as in , ES Head, Portainer, WebTTY, and Spiderfoot all load fine, so does the pink navbar at the top, however the dashboard list and Kibana dashboard do not load, simply providing a timeout error.

Based on the architecture diagram, it seems as though only Port 64297 is required to be exposed for external dashboard access. Am i missing something here?

Appreciate the assistance :)

Cheers,
Ray

### Basic support information

- What T-Pot version are you currently using? 17.10
- Are you running on a Intel NUC or a VM? VMWare
- How long has your installation been running? 2 Days
- Did you install any upgrades or packages? No
- Did you modify any scripts? No
- Have you turned persistence on/off? No, however extended to 90 Days
- How much RAM available (login via ssh and run `htop`)? 4GB Free
- How much stress are the CPUs under (login via ssh and run `htop`)? Minimal; Load 1.20, 1.14, 1.24
- How much swap space is being used (login via ssh and run `htop`)? 12MB
- How much free disk space is available (login via ssh and run `sudo df -h`)? 87% free
- What is the current container status (login via ssh and run `sudo start.sh`)? dps.sh reports all healthy

**Comment by t3chn0m4g3** [comment]
@UncleRaymondo This might need some tinkering with regard to the NGINX reqwrite rules `https://github.com/dtag-dev-sec/tpotce/blob/master/host/etc/nginx/tpotweb.conf`. Please provide NGINX logs (`/var/log/nginx`).

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved with.

**Comment by UncleRaymondo** [comment]
Sorry mate, was meant to get back to you on this one...
Having a look at the rewrite rules, they seem fine but I'm not an expert with NGINX - They haven't been changed, still default.
There's nothing out of the ordinary in the access log - Error log contains nothing in relation to this (does have another error which I will create a new issue for)

The GET /kibana seems to be giving a 301 and that's it...

![kibana](https://user-images.githubusercontent.com/5147133/37442379-1cc2a8d4-285a-11e8-8db3-d27113ba94e0.png)

Thoughts?

**Comment by UncleRaymondo** [comment]
OK - I've tried playing with the proxy_pass / rewrite rules for /kibana, even trying the proxy_redirect and proxy_set_header attributes, but still cannot get the site to load from the outside..

The URL which points to the different external IP than the honeypot external IP redirects 443 to 64297 on the firewall using a NAT Rule; this works fine.

What is weird though is even though NGINX shows the /kibana proxy_pass rule going to http://localhost:64296, fiddler shows that when accessing the URL from the outside, it's trying to get to http://<URL>:64297/kibana

I'm no expert in NGINX so I'm not too sure why this behaviour... do you have any clues that I can look at or try?

**Comment by hvdkooij** [comment]
Website redirects contain absolute links. Including the port information. That might be the problem. But the redirect is supposed to contain the absolute link. See also: https://en.wikipedia.org/wiki/HTTP_301
